use test2.university;

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Introduction to Computing', 'ICT2-01', 3, 2, 60, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Programming Fundamentals', 'ICT2-02', 3, 2, 48, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mathematics for Computing', 'ICT2-03', 3, 2, 64, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer Systems Basics', 'ICT2-04', 3, 2, 8, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Digital Logic', 'ICT2-05', 3, 2, 68, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Data Structures', 'ICT2-06', 3, 2, 45, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Algorithms', 'ICT2-07', 3, 2, 60, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Database Systems', 'ICT2-08', 3, 2, 48, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Operating Systems', 'ICT2-09', 3, 2, 64, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Networking Basics', 'ICT2-10', 3, 2, 8, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Engineering', 'ICT2-11', 3, 2, 68, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Web Development', 'ICT2-12', 3, 2, 45, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mobile App Development', 'ICT2-13', 3, 2, 60, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Cloud Computing Basics', 'ICT2-14', 3, 2, 48, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Cybersecurity Fundamentals', 'ICT2-15', 3, 2, 64, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Human-Computer Interaction', 'ICT2-16', 3, 2, 8, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Machine Learning Basics', 'ICT2-17', 3, 2, 68, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Data Analytics', 'ICT2-18', 3, 2, 45, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Programming Paradigms', 'ICT2-19', 3, 2, 60, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Algorithms Advanced', 'ICT2-20', 3, 2, 48, 4);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Database Design', 'ICT2-21', 3, 2, 64, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Testing', 'ICT2-22', 3, 2, 8, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Network Security', 'ICT2-23', 3, 2, 68, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Big Data Analytics', 'ICT2-24', 3, 2, 45, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Internet of Things', 'ICT2-25', 3, 2, 60, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Advanced Programming', 'ICT2-26', 3, 2, 48, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer Graphics', 'ICT2-27', 3, 2, 64, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Simulation & Modeling', 'ICT2-28', 3, 2, 8, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Architecture', 'ICT2-29', 3, 2, 68, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Project', 'ICT2-30', 3, 2, 45, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Introduction to Computing', 'ICT5-01', 3, 5, 39, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Programming Fundamentals', 'ICT5-02', 3, 5, 64, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mathematics for Computing', 'ICT5-03', 3, 5, 59, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer Systems Basics', 'ICT5-04', 3, 5, 65, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Digital Logic', 'ICT5-05', 3, 5, 8, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Data Structures', 'ICT5-06', 3, 5, 21, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Algorithms', 'ICT5-07', 3, 5, 39, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Database Systems', 'ICT5-08', 3, 5, 64, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Operating Systems', 'ICT5-09', 3, 5, 59, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Networking Basics', 'ICT5-10', 3, 5, 65, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Engineering', 'ICT5-11', 3, 5, 8, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Web Development', 'ICT5-12', 3, 5, 21, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mobile App Development', 'ICT5-13', 3, 5, 39, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Cloud Computing Basics', 'ICT5-14', 3, 5, 64, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Cybersecurity Fundamentals', 'ICT5-15', 3, 5, 59, 3);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Human-Computer Interaction', 'ICT5-16', 3, 5, 65, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Machine Learning Basics', 'ICT5-17', 3, 5, 8, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Data Analytics', 'ICT5-18', 3, 5, 21, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Programming Paradigms', 'ICT5-19', 3, 5, 39, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Algorithms Advanced', 'ICT5-20', 3, 5, 64, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Database Design', 'ICT5-21', 3, 5, 59, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Testing', 'ICT5-22', 3, 5, 65, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Network Security', 'ICT5-23', 3, 5, 8, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Big Data Analytics', 'ICT5-24', 3, 5, 21, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Internet of Things', 'ICT5-25', 3, 5, 39, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Advanced Programming', 'ICT5-26', 3, 5, 64, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer Graphics', 'ICT5-27', 3, 5, 59, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Simulation & Modeling', 'ICT5-28', 3, 5, 65, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Architecture', 'ICT5-29', 3, 5, 8, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Project', 'ICT5-30', 3, 5, 21, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Introduction to Computing', 'ICT6-01', 3, 6, 26, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Programming Fundamentals', 'ICT6-02', 3, 6, 8, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mathematics for Computing', 'ICT6-03', 3, 6, 42, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer Systems Basics', 'ICT6-04', 3, 6, 65, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Digital Logic', 'ICT6-05', 3, 6, 58, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Data Structures', 'ICT6-06', 3, 6, 24, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Algorithms', 'ICT6-07', 3, 6, 26, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Database Systems', 'ICT6-08', 3, 6, 8, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Operating Systems', 'ICT6-09', 3, 6, 42, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Networking Basics', 'ICT6-10', 3, 6, 65, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Engineering', 'ICT6-11', 3, 6, 58, 3);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Web Development', 'ICT6-12', 3, 6, 24, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mobile App Development', 'ICT6-13', 3, 6, 26, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Cloud Computing Basics', 'ICT6-14', 3, 6, 8, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Cybersecurity Fundamentals', 'ICT6-15', 3, 6, 42, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Human-Computer Interaction', 'ICT6-16', 3, 6, 65, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Machine Learning Basics', 'ICT6-17', 3, 6, 58, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Data Analytics', 'ICT6-18', 3, 6, 24, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Programming Paradigms', 'ICT6-19', 3, 6, 26, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Algorithms Advanced', 'ICT6-20', 3, 6, 8, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Database Design', 'ICT6-21', 3, 6, 42, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Testing', 'ICT6-22', 3, 6, 65, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Network Security', 'ICT6-23', 3, 6, 58, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Big Data Analytics', 'ICT6-24', 3, 6, 24, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Internet of Things', 'ICT6-25', 3, 6, 26, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Advanced Programming', 'ICT6-26', 3, 6, 8, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer Graphics', 'ICT6-27', 3, 6, 42, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Simulation & Modeling', 'ICT6-28', 3, 6, 65, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Software Architecture', 'ICT6-29', 3, 6, 58, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Project', 'ICT6-30', 3, 6, 24, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Principles of Management', 'BUS7-01', 3, 7, 28, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Organizational Behavior', 'BUS7-02', 3, 7, 22, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Financial Accounting', 'BUS7-03', 3, 7, 65, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Marketing Fundamentals', 'BUS7-04', 3, 7, 47, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Law', 'BUS7-05', 3, 7, 29, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Operations Management', 'BUS7-06', 3, 7, 6, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Strategic Management', 'BUS7-07', 3, 7, 28, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Human Resource Management', 'BUS7-08', 3, 7, 22, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Ethics', 'BUS7-09', 3, 7, 65, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Project Management', 'BUS7-10', 3, 7, 47, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Entrepreneurship', 'BUS7-11', 3, 7, 29, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Corporate Finance', 'BUS7-12', 3, 7, 6, 3);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Analytics', 'BUS7-13', 3, 7, 28, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Leadership Skills', 'BUS7-14', 3, 7, 22, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Consumer Behavior', 'BUS7-15', 3, 7, 65, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Supply Chain Management', 'BUS7-16', 3, 7, 47, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Investment Analysis', 'BUS7-17', 3, 7, 29, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Management Information Systems', 'BUS7-18', 3, 7, 6, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Negotiation Skills', 'BUS7-19', 3, 7, 28, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Communication', 'BUS7-20', 3, 7, 22, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('International Business', 'BUS7-21', 3, 7, 65, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Digital Marketing', 'BUS7-22', 3, 7, 47, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Economics for Managers', 'BUS7-23', 3, 7, 29, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Risk Management', 'BUS7-24', 3, 7, 6, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Corporate Strategy', 'BUS7-25', 3, 7, 28, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Research Methods', 'BUS7-26', 3, 7, 22, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Decision Making', 'BUS7-27', 3, 7, 65, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Brand Management', 'BUS7-28', 3, 7, 47, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Service Management', 'BUS7-29', 3, 7, 29, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Project', 'BUS7-30', 3, 7, 6, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Principles of Management', 'BUS8-01', 3, 8, 45, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Organizational Behavior', 'BUS8-02', 3, 8, 58, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Financial Accounting', 'BUS8-03', 3, 8, 35, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Marketing Fundamentals', 'BUS8-04', 3, 8, 53, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Law', 'BUS8-05', 3, 8, 41, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Operations Management', 'BUS8-06', 3, 8, 56, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Strategic Management', 'BUS8-07', 3, 8, 45, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Human Resource Management', 'BUS8-08', 3, 8, 58, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Ethics', 'BUS8-09', 3, 8, 35, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Project Management', 'BUS8-10', 3, 8, 53, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Entrepreneurship', 'BUS8-11', 3, 8, 41, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Corporate Finance', 'BUS8-12', 3, 8, 56, 3);






INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Analytics', 'BUS8-13', 3, 8, 45, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Leadership Skills', 'BUS8-14', 3, 8, 58, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Consumer Behavior', 'BUS8-15', 3, 8, 35, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Supply Chain Management', 'BUS8-16', 3, 8, 53, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Investment Analysis', 'BUS8-17', 3, 8, 41, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Management Information Systems', 'BUS8-18', 3, 8, 56, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Negotiation Skills', 'BUS8-19', 3, 8, 45, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Communication', 'BUS8-20', 3, 8, 58, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('International Business', 'BUS8-21', 3, 8, 35, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Digital Marketing', 'BUS8-22', 3, 8, 53, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Economics for Managers', 'BUS8-23', 3, 8, 41, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Risk Management', 'BUS8-24', 3, 8, 56, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Corporate Strategy', 'BUS8-25', 3, 8, 45, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Research Methods', 'BUS8-26', 3, 8, 58, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Decision Making', 'BUS8-27', 3, 8, 35, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Brand Management', 'BUS8-28', 3, 8, 53, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Service Management', 'BUS8-29', 3, 8, 41, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Project', 'BUS8-30', 3, 8, 56, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Principles of Management', 'BUS9-01', 3, 9, 34, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Organizational Behavior', 'BUS9-02', 3, 9, 3, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Financial Accounting', 'BUS9-03', 3, 9, 25, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Marketing Fundamentals', 'BUS9-04', 3, 9, 52, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Law', 'BUS9-05', 3, 9, 57, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Operations Management', 'BUS9-06', 3, 9, 61, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Strategic Management', 'BUS9-07', 3, 9, 34, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Human Resource Management', 'BUS9-08', 3, 9, 3, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Ethics', 'BUS9-09', 3, 9, 25, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Project Management', 'BUS9-10', 3, 9, 52, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Entrepreneurship', 'BUS9-11', 3, 9, 57, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Corporate Finance', 'BUS9-12', 3, 9, 61, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Analytics', 'BUS9-13', 3, 9, 34, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Leadership Skills', 'BUS9-14', 3, 9, 3, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Consumer Behavior', 'BUS9-15', 3, 9, 25, 3);


INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Supply Chain Management', 'BUS9-16', 3, 9, 52, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Investment Analysis', 'BUS9-17', 3, 9, 57, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Management Information Systems', 'BUS9-18', 3, 9, 61, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Negotiation Skills', 'BUS9-19', 3, 9, 34, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Communication', 'BUS9-20', 3, 9, 3, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('International Business', 'BUS9-21', 3, 9, 25, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Digital Marketing', 'BUS9-22', 3, 9, 52, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Economics for Managers', 'BUS9-23', 3, 9, 57, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Risk Management', 'BUS9-24', 3, 9, 61, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Corporate Strategy', 'BUS9-25', 3, 9, 34, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Business Research Methods', 'BUS9-26', 3, 9, 3, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Decision Making', 'BUS9-27', 3, 9, 25, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Brand Management', 'BUS9-28', 3, 9, 52, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Service Management', 'BUS9-29', 3, 9, 57, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Project', 'BUS9-30', 3, 9, 61, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Engineering Mathematics', 'ENG10-01', 3, 10, 48, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mechanics of Materials', 'ENG10-02', 3, 10, 64, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Thermodynamics', 'ENG10-03', 3, 10, 67, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Fluid Mechanics', 'ENG10-04', 3, 10, 60, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electrical Circuits', 'ENG10-05', 3, 10, 37, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Signals and Systems', 'ENG10-06', 3, 10, 25, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Control Systems', 'ENG10-07', 3, 10, 48, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Material Science', 'ENG10-08', 3, 10, 64, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Manufacturing Processes', 'ENG10-09', 3, 10, 67, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Engineering Design', 'ENG10-10', 3, 10, 60, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electronics', 'ENG10-11', 3, 10, 37, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Embedded Systems', 'ENG10-12', 3, 10, 25, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Robotics', 'ENG10-13', 3, 10, 48, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Instrumentation', 'ENG10-14', 3, 10, 64, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Machine Design', 'ENG10-15', 3, 10, 67, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Structural Analysis', 'ENG10-16', 3, 10, 60, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Heat Transfer', 'ENG10-17', 3, 10, 37, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Environmental Engineering', 'ENG10-18', 3, 10, 25, 4);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Project Management', 'ENG10-19', 3, 10, 48, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer-Aided Design', 'ENG10-20', 3, 10, 64, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Renewable Energy Systems', 'ENG10-21', 3, 10, 67, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Automotive Engineering', 'ENG10-22', 3, 10, 60, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mechatronics', 'ENG10-23', 3, 10, 37, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Industrial Automation', 'ENG10-24', 3, 10, 25, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Civil Engineering Basics', 'ENG10-25', 3, 10, 48, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electrical Machines', 'ENG10-26', 3, 10, 64, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Power Systems', 'ENG10-27', 3, 10, 67, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Design', 'ENG10-28', 3, 10, 60, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Simulation & Modeling', 'ENG10-29', 3, 10, 37, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Final Year Project', 'ENG10-30', 3, 10, 25, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Engineering Mathematics', 'ENG11-01', 3, 11, 61, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mechanics of Materials', 'ENG11-02', 3, 11, 40, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Thermodynamics', 'ENG11-03', 3, 11, 51, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Fluid Mechanics', 'ENG11-04', 3, 11, 47, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electrical Circuits', 'ENG11-05', 3, 11, 31, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Signals and Systems', 'ENG11-06', 3, 11, 30, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Control Systems', 'ENG11-07', 3, 11, 61, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Material Science', 'ENG11-08', 3, 11, 40, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Manufacturing Processes', 'ENG11-09', 3, 11, 51, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Engineering Design', 'ENG11-10', 3, 11, 47, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electronics', 'ENG11-11', 3, 11, 31, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Embedded Systems', 'ENG11-12', 3, 11, 30, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Robotics', 'ENG11-13', 3, 11, 61, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Instrumentation', 'ENG11-14', 3, 11, 40, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Machine Design', 'ENG11-15', 3, 11, 51, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Structural Analysis', 'ENG11-16', 3, 11, 47, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Heat Transfer', 'ENG11-17', 3, 11, 31, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Environmental Engineering', 'ENG11-18', 3, 11, 30, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Project Management', 'ENG11-19', 3, 11, 61, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer-Aided Design', 'ENG11-20', 3, 11, 40, 4);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Renewable Energy Systems', 'ENG11-21', 3, 11, 51, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Automotive Engineering', 'ENG11-22', 3, 11, 47, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mechatronics', 'ENG11-23', 3, 11, 31, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Industrial Automation', 'ENG11-24', 3, 11, 30, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Civil Engineering Basics', 'ENG11-25', 3, 11, 61, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electrical Machines', 'ENG11-26', 3, 11, 40, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Power Systems', 'ENG11-27', 3, 11, 51, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Design', 'ENG11-28', 3, 11, 47, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Simulation & Modeling', 'ENG11-29', 3, 11, 31, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Final Year Project', 'ENG11-30', 3, 11, 30, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Engineering Mathematics', 'ENG12-01', 3, 12, 42, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mechanics of Materials', 'ENG12-02', 3, 12, 62, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Thermodynamics', 'ENG12-03', 3, 12, 3, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Fluid Mechanics', 'ENG12-04', 3, 12, 43, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electrical Circuits', 'ENG12-05', 3, 12, 40, 1);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Signals and Systems', 'ENG12-06', 3, 12, 26, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Control Systems', 'ENG12-07', 3, 12, 42, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Material Science', 'ENG12-08', 3, 12, 62, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Manufacturing Processes', 'ENG12-09', 3, 12, 3, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Engineering Design', 'ENG12-10', 3, 12, 43, 2);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electronics', 'ENG12-11', 3, 12, 40, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Embedded Systems', 'ENG12-12', 3, 12, 26, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Robotics', 'ENG12-13', 3, 12, 42, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Instrumentation', 'ENG12-14', 3, 12, 62, 3);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Machine Design', 'ENG12-15', 3, 12, 3, 3);

INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Structural Analysis', 'ENG12-16', 3, 12, 43, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Heat Transfer', 'ENG12-17', 3, 12, 40, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Environmental Engineering', 'ENG12-18', 3, 12, 26, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Project Management', 'ENG12-19', 3, 12, 42, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Computer-Aided Design', 'ENG12-20', 3, 12, 62, 4);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Renewable Energy Systems', 'ENG12-21', 3, 12, 3, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Automotive Engineering', 'ENG12-22', 3, 12, 43, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Mechatronics', 'ENG12-23', 3, 12, 40, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Industrial Automation', 'ENG12-24', 3, 12, 26, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Civil Engineering Basics', 'ENG12-25', 3, 12, 42, 5);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Electrical Machines', 'ENG12-26', 3, 12, 62, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Power Systems', 'ENG12-27', 3, 12, 3, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Capstone Design', 'ENG12-28', 3, 12, 43, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Simulation & Modeling', 'ENG12-29', 3, 12, 40, 6);
INSERT INTO module (moduleName, moduleCode, moduleCredits, courseId, lecturerId, moduleSemester) VALUES ('Final Year Project', 'ENG12-30', 3, 12, 26, 6);