CREATE TABLE login (
    loginId INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    role ENUM('STUDENT','LECTURER','COORDINATOR','ADMIN') NOT NULL,
    userId INT NOT NULL,   -- ID of the actual user
    userType ENUM('STUDENT','LECTURER','COORDINATOR','ADMIN') NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
