package ca.cloudace.backend.controller;

import lombok.Data;

@Data
public class CourseEnrolmentDTO {

    private Long courseEnrolId;
    private Long studentId;
    private Long courseId;
    private String courseEnrolDate;
    private String courseEnrolStatus;
    private String courseEnrolGraduation;

    // Constructors, getters, and setters can be generated by Lombok

}
