package ca.cloudace.backend.controller;

import lombok.Data;

/**
 * Data Transfer Object for Department entity.
 * This class is used to transfer department data between client and server.
 * It includes fields for department code, department name, faculty ID, and lecturer ID.
 *  @Data annotation from Lombok is used to generate boilerplate code like getters, setters, toString, equals, and hashCode methods.
 */

@Data
public class DepartmentDTO {
    private String departmentCode;
    private String departmentName;
    private Long facultyId;
    private Integer lecturerId;
    private Long departmentId;


    // Constructors, getters, and setters can be generated by Lombok
    public DepartmentDTO() {
    }

    public DepartmentDTO(Long departmentId, String departmentCode, String departmentName, Long facultyId, Integer lecturerId) {
        this.departmentId = departmentId;
        this.departmentCode = departmentCode;
        this.departmentName = departmentName;
        this.facultyId = facultyId;
        this.lecturerId = lecturerId;
    }

    // Getters and Setters (normally taken care by Lombok's @Data; but included here for clarity)
    public String getDepartmentCode() {
        return departmentCode;
    }
    public void setDepartmentCode(String departmentCode) {
        this.departmentCode = departmentCode;
    }
    public String getDepartmentName() {
        return departmentName;
    }
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Long getFacultyId() {
        return facultyId;
    }
    public void setFacultyId(Long facultyId) {
        this.facultyId = facultyId;
    }
    public Integer getLecturerId() {
        return lecturerId;
    }
    public void setLecturerId(Integer lecturerId) {
        this.lecturerId = lecturerId;
    }

    public Long getDepartmentId() {
        return departmentId;
    }
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

}
