package ca.cloudace.backend.controller;

import lombok.Data;

/**
 * Data Transfer Object for ModuleEnrolment
 * We will need this to avoid circular references in JSON serialization
 * when ModuleEnrolment contains references to Student and Module entities.
 * we will need to get details of students and modules separately using their
 * respective controllers.
 */
@Data
public class ModuleEnrolmentDTO {

    private Long enrolmentId;
    private Long studentId; // we will to get details of student separately
    private Long moduleId; // we will to get details of module separately
    private String enrolmentDate; // Use String to simplify date handling in DTO
    private String grade;
    private String status;

    // Constructors, getters, and setters can be generated by Lombok
    public ModuleEnrolmentDTO() {
    }

    public ModuleEnrolmentDTO(Long enrolmentId, Long studentId, Long moduleId, String enrolmentDate, String grade,
            String status) {
        this.enrolmentId = enrolmentId;
        this.studentId = studentId;
        this.moduleId = moduleId;
        this.enrolmentDate = enrolmentDate;
        this.grade = grade;
        this.status = status;
    }

    // getters and setters are generated by Lombok @Data annotation

}
